---

- name: Installing Python3
  dnf:
    name: python3
    state: latest

- name: Installing pip
  dnf: 
    name: python3-pip
    state: latest

- name: Upgarding pip
  pip: 
    name: pip
    extra_args: --upgrade

- name: Install TensorFlow
  pip: 
    name: tensorflow
